/**
 * Seed script — generates ~300 simulated telemetry records
 * across 3 experiments with realistic, gradually varying values.
 *
 * IMPORTANT: All data generated by this script is SIMULATED.
 * It is for software development and testing purposes only.
 * Do not present simulated values as real experimental results.
 *
 * The generation model mirrors scripts/liveSimulator.js — that file is the
 * reference and carries the full explanation of each relationship. Keep the
 * constants below in step with it so seeded history and live telemetry sit on
 * the same scale.
 *
 * Usage: node scripts/seedData.js
 */

require('dotenv').config();
const mongoose = require('mongoose');
const Telemetry = require('../src/models/Telemetry');

const MONGO_URI = process.env.MONGO_URI;

if (!MONGO_URI) {
    console.error('Error: MONGO_URI is not set in .env');
    process.exit(1);
}

/* ── SIMULATOR-ONLY rig model (see liveSimulator.js) ────────────────────
   V = I × 41 + 2 is the project's calibration relationship, applied here so
   seeded voltage/current/power are self-consistent. NOT confirmed for the real
   hardware — see liveSimulator.js for the full note.                      */
const CAL_SLOPE = 41;
const CAL_INTERCEPT = 2;

const WIND_CUT_IN = 1.5;
const WIND_RATED = 4.0;
const WIND_CUT_OUT = 9.0;
const CURRENT_RATED = 0.29;
const CURRENT_MAX = 0.42;
const PITCH_OPTIMUM = 4;
const PITCH_FALLOFF = 26;

const STEPS_PER_DEGREE = 50;

const WAVE_ROLL_PERIOD = 9.5;
const WAVE_PITCH_PERIOD = 7.3;
const WAVE_HEAVE_PERIOD = 10.0;

const SAMPLE_SECONDS = 5; // seed records are spaced 5 s apart

// Experiment definitions
const experiments = [
    {
        experimentId: 'EXP-001',
        pitchAngle: 0,
        windSpeedRange: [2, 4],     // m/s
        recordCount: 100,
        description: 'Pitch 0° — Low wind speed range',
    },
    {
        experimentId: 'EXP-002',
        pitchAngle: 4,
        windSpeedRange: [3, 6],
        recordCount: 100,
        description: 'Pitch 4° — Medium wind speed range',
    },
    {
        experimentId: 'EXP-003',
        pitchAngle: 20,
        windSpeedRange: [5, 8],
        recordCount: 100,
        description: 'Pitch 20° — High wind speed range',
    },
];

const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));
const round = (v, dp) => parseFloat(v.toFixed(dp));

/**
 * Generate a value that gradually varies from the previous value.
 * Simulates sensor readings that change smoothly over time.
 */
function gradualValue(previous, min, max, maxStep) {
    const step = (Math.random() - 0.5) * 2 * maxStep;
    return clamp(previous + step, min, max);
}

function noise(sigma) {
    const u = Math.random() || 1e-9;
    const v = Math.random();
    return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v) * sigma;
}

/** Wind speed and blade pitch → generated current (simulator-only model). */
function currentFor(windSpeed, pitchAngle) {
    if (windSpeed <= WIND_CUT_IN) return 0;

    let base;
    if (windSpeed <= WIND_RATED) {
        const span = (windSpeed - WIND_CUT_IN) / (WIND_RATED - WIND_CUT_IN);
        base = CURRENT_RATED * Math.pow(span, 1.5);
    } else {
        const span = clamp((windSpeed - WIND_RATED) / (WIND_CUT_OUT - WIND_RATED), 0, 1);
        base = CURRENT_RATED + (CURRENT_MAX - CURRENT_RATED) * span;
    }

    const offset = (pitchAngle - PITCH_OPTIMUM) / PITCH_FALLOFF;
    const pitchEfficiency = clamp(1 - offset * offset, 0.15, 1);
    return base * pitchEfficiency;
}

/**
 * Generate records for a single experiment.
 *
 * @param experiment   the profile above
 * @param stepOffset   running sample index, so timeStep is unique and
 *                     increasing across the whole seeded set
 */
function generateExperiment(experiment, stepOffset) {
    const records = [];
    const { experimentId, pitchAngle, windSpeedRange, recordCount } = experiment;

    // Start timestamp: progressing forward in SAMPLE_SECONDS intervals
    const startTime = new Date(Date.now() - recordCount * SAMPLE_SECONDS * 1000);

    let windSpeed = (windSpeedRange[0] + windSpeedRange[1]) / 2;
    let current = currentFor(windSpeed, pitchAngle);
    let yawRate = 0;

    // Stepper position for a fixed-pitch experiment (0° → 0, 4° → 200, 20° → 1000)
    const stepperBase = Math.round(pitchAngle * STEPS_PER_DEGREE);

    for (let i = 0; i < recordCount; i++) {
        const elapsed = i * SAMPLE_SECONDS; // seconds into the experiment

        // Wind drifts gradually within the experiment's range
        windSpeed = gradualValue(windSpeed, windSpeedRange[0], windSpeedRange[1], 0.3);

        // Current follows wind through the same curve the live simulator uses
        const target = currentFor(windSpeed, pitchAngle);
        current += (target - current) * 0.5;
        const currentNow = Math.max(0, current + noise(0.002));

        // Voltage from the calibration, power from V × I (matching the backend)
        const voltage = currentNow > 0 ? CAL_SLOPE * currentNow + CAL_INTERCEPT : 0;
        const power = voltage * currentNow;

        // Stepper holds position, with a little mechanical play
        const stepperPosition = stepperBase + Math.round(noise(1.2));

        // Platform motion — same wave model as the live simulator
        const seaState = clamp(
            (windSpeed - windSpeedRange[0]) / Math.max(0.1, windSpeedRange[1] - windSpeedRange[0]),
            0, 1
        );
        const rollAmp = 0.6 + 1.8 * seaState;
        const platPitchAmp = 0.4 + 1.3 * seaState;
        const heaveAmp = 0.02 + 0.05 * seaState;

        const wRoll = (2 * Math.PI) / WAVE_ROLL_PERIOD;
        const wPitch = (2 * Math.PI) / WAVE_PITCH_PERIOD;
        const wHeave = (2 * Math.PI) / WAVE_HEAVE_PERIOD;

        const rollAngle = rollAmp * Math.sin(wRoll * elapsed);
        const platPitchAngle = platPitchAmp * Math.sin(wPitch * elapsed + 1.1);

        const gyroX = rollAmp * wRoll * Math.cos(wRoll * elapsed) + noise(0.05);
        const gyroY = platPitchAmp * wPitch * Math.cos(wPitch * elapsed + 1.1) + noise(0.05);
        yawRate = gradualValue(yawRate, -1.5, 1.5, 0.2);
        const gyroZ = yawRate + noise(0.04);

        const rollRad = (rollAngle * Math.PI) / 180;
        const pitchRad = (platPitchAngle * Math.PI) / 180;
        const heave = heaveAmp * Math.sin(wHeave * elapsed + 0.4);

        const accelerometerX = -Math.sin(pitchRad) + noise(0.004);
        const accelerometerY = Math.sin(rollRad) * Math.cos(pitchRad) + noise(0.004);
        const accelerometerZ = Math.cos(rollRad) * Math.cos(pitchRad) + heave + noise(0.004);

        const timestamp = new Date(startTime.getTime() + elapsed * 1000);

        records.push({
            experimentId,
            source: 'simulator',
            timestamp,
            timeStep: stepOffset + i,
            windSpeed: round(windSpeed, 3),
            pitchAngle,
            stepperPosition,
            voltage: round(voltage, 3),
            current: round(currentNow, 4),
            power: round(power, 4),
            gyroX: round(gyroX, 3),
            gyroY: round(gyroY, 3),
            gyroZ: round(gyroZ, 3),
            accelerometerX: round(accelerometerX, 4),
            accelerometerY: round(accelerometerY, 4),
            accelerometerZ: round(accelerometerZ, 4),
        });
    }

    return records;
}

async function seed() {
    try {
        console.log('Connecting to MongoDB...');
        await mongoose.connect(MONGO_URI);
        console.log('MongoDB connected');

        // Clear existing simulated data
        const deleted = await Telemetry.deleteMany({ source: 'simulator' });
        console.log(`Cleared ${deleted.deletedCount} existing simulated records`);

        let totalInserted = 0;

        for (const experiment of experiments) {
            console.log(`\nGenerating: ${experiment.description}`);
            const records = generateExperiment(experiment, totalInserted);
            await Telemetry.insertMany(records);
            console.log(`  Inserted ${records.length} records for ${experiment.experimentId}`);
            totalInserted += records.length;
        }

        console.log(`\n========================================`);
        console.log(`SEED COMPLETE`);
        console.log(`Total records inserted: ${totalInserted}`);
        console.log(`Source: simulator (SIMULATED DATA)`);
        console.log(`========================================`);
        console.log(`\nExperiments:`);
        for (const exp of experiments) {
            console.log(`  ${exp.experimentId}: pitch=${exp.pitchAngle}°, wind=${exp.windSpeedRange[0]}-${exp.windSpeedRange[1]} m/s`);
        }

        await mongoose.connection.close();
        console.log('\nMongoDB connection closed');
        process.exit(0);
    } catch (error) {
        console.error('Seed error:', error.message);
        process.exit(1);
    }
}

seed();
